export const LOAD_LATEST = "LOAD_LATEST";
export const LOAD_LATEST_SUCCESS = "LOAD_LATEST_SUCCESS";
export const LOAD_LATEST_ERROR = "LOAD_LATEST_ERROR";

export const LOAD_UPCOMING = "LOAD_UPCOMING";
export const LOAD_UPCOMING_SUCCESS = "LOAD_UPCOMING_SUCCESS";
export const LOAD_UPCOMING_ERROR = "LOAD_UPCOMING_ERROR";

export const LOAD_POPULAR = "LOAD_POPULAR";
export const LOAD_POPULAR_SUCCESS = "LOAD_POPULAR_SUCCESS";
export const LOAD_POPULAR_ERROR = "LOAD_POPULAR_ERROR";
